### ISSUE TITLE
[Request] Ability to disable skipping item acquisition cutscenes

### ISSUE THREAD

**Issue by doctorsangria** [blakespangenberg/metroid-prime-plandomizer#1]
Much like the option to disable skipping HUD memos for item pickups, but for the cutscene itself too. Personally I would like the ability to generate near-vanilla ISOs while still using your quickplay feature (which is really really convenient for quickly jumping in and practicing speedruns in Dolphin).

**Comment by toasterparty** [comment]
The item acquisition cutscenes are supposed to be skipped already. Are you seeing them?

**Comment by toasterparty** [comment]
I just read this a second time and caught the double negative ("disable skipping").

This is a feature in a future unreleased version.
